//! macOS 클립보드 감시 — `NSPasteboard.changeCount` **적응형 폴링** (T-14e).
//!
//! 외부 crate 없이 objc 런타임을 직접 부른다([`crate::paste`]의 appkit 선례 · DR-8).
//!
//! ## 왜 폴링인가
//!
//! macOS에는 클립보드 변경 **이벤트가 없다**([docs/20 §3-1](../../../docs/20-implementation-spec.md)).
//! 유일한 신호가 `changeCount`(복사마다 +1)다. 그래서:
//!
//! - **활동 직후 200ms · 유휴로 갈수록 1s까지** 주기를 늘린다(DR-9 상주 예산 — 유휴 비용은
//!   1초당 objc 호출 1회까지 내려간다).
//! - `changeCount`가 **바뀔 때만** 내용을 읽는다 — 평소에는 데이터에 손대지 않는다.
//!
//! ## ⚠️ Windows 결함 ⑫의 교훈을 처음부터 적용한다
//!
//! 복사하는 앱이 파스텔보드를 *비우고 → 채우는* 틈에 읽으면 **표현 0개** 스냅숏이 온다.
//! 그때 `changeCount`를 "처리했다"고 기록하면(빈 스냅숏의 `LAST_SEQ` 오염 — 08-27 해부)
//! 채워진 진짜 내용은 번호가 그대로라 **영영 유실**된다.
//! → **내용 없는 스냅숏은 미처리**로 두고 다음 틱에 다시 읽는다.
//!
//! ## 민감 표식 (docs/20 §297)
//!
//! | UTI | 뜻 |
//! |---|---|
//! | `org.nspasteboard.ConcealedType` | 비밀번호 등 민감 — 기록 금지 |
//! | `org.nspasteboard.TransientType` | 일시적 — 이력에 남기지 마 |
//! | `org.nspasteboard.AutoGeneratedType` | 사용자가 복사한 게 아님 |
//!
//! 셋 다 **존재만으로** `concealed`다(Windows `Exclude…` 표식과 동일 취급 · fail-closed).
//! 표식이 보이면 **날바이트를 읽지 않는다** — 이름만 담아도 게이트 판정에는 충분하다.

use nclip_core::{ClipSnapshot, RawRep, WatchError};

/// 변화가 있을 때 부를 것 — 스레드를 건너가므로 `Send`.
pub type Sink = Box<dyn Fn(ClipSnapshot) + Send>;

/// 활동 직후 폴링 주기.
const ACTIVE_MS: u64 = 200;
/// 유휴 상한 주기.
const IDLE_MAX_MS: u64 = 1000;
/// 이만큼 조용하면(틱 수) 주기를 늘리기 시작한다 — 200ms × 25 = 5초.
const IDLE_AFTER_TICKS: u32 = 25;
/// 유휴 진입 후 틱마다 늘리는 양.
const IDLE_STEP_MS: u64 = 100;

// ───────────────────────────── objc 런타임 (paste.rs appkit 선례)

type Id = *mut core::ffi::c_void;

#[link(name = "objc", kind = "dylib")]
extern "C" {
    fn objc_getClass(name: *const u8) -> Id;
    fn sel_registerName(name: *const u8) -> Id;
    fn objc_msgSend();
    fn objc_autoreleasePoolPush() -> Id;
    fn objc_autoreleasePoolPop(ctx: Id);
}

// AppKit 프레임워크를 링크해야 NSPasteboard·NSWorkspace 클래스가 로드된다.
#[link(name = "AppKit", kind = "framework")]
extern "C" {}

// ⚠️ 크레이트가 `forbid(unsafe_op_in_unsafe_fn)` — `unsafe fn` 안에서도 블록이 필요하다.
unsafe fn cls(name: &[u8]) -> Id {
    unsafe { objc_getClass(name.as_ptr()) }
}
unsafe fn sel(name: &[u8]) -> Id {
    unsafe { sel_registerName(name.as_ptr()) }
}

/// `[recv sel]` → 객체.
unsafe fn send0(recv: Id, s: &[u8]) -> Id {
    unsafe {
        let f: unsafe extern "C" fn(Id, Id) -> Id = core::mem::transmute(objc_msgSend as *const ());
        f(recv, sel(s))
    }
}

/// `[recv sel]` → `NSInteger`/`NSUInteger`(포인터 폭 정수).
unsafe fn send0_int(recv: Id, s: &[u8]) -> isize {
    unsafe {
        let f: unsafe extern "C" fn(Id, Id) -> isize =
            core::mem::transmute(objc_msgSend as *const ());
        f(recv, sel(s))
    }
}

/// `[recv sel:obj]` → 객체.
unsafe fn send1(recv: Id, s: &[u8], arg: Id) -> Id {
    unsafe {
        let f: unsafe extern "C" fn(Id, Id, Id) -> Id =
            core::mem::transmute(objc_msgSend as *const ());
        f(recv, sel(s), arg)
    }
}

/// `[recv sel:idx]` → 객체(`objectAtIndex:`).
unsafe fn send1_idx(recv: Id, s: &[u8], idx: usize) -> Id {
    unsafe {
        let f: unsafe extern "C" fn(Id, Id, usize) -> Id =
            core::mem::transmute(objc_msgSend as *const ());
        f(recv, sel(s), idx)
    }
}

/// `NSString` → 러스트 문자열(`UTF8String`). 실패하면 `None`.
unsafe fn ns_string(ns: Id) -> Option<String> {
    if ns.is_null() {
        return None;
    }
    unsafe {
        let f: unsafe extern "C" fn(Id, Id) -> *const core::ffi::c_char =
            core::mem::transmute(objc_msgSend as *const ());
        let p = f(ns, sel(b"UTF8String\0"));
        if p.is_null() {
            return None;
        }
        Some(core::ffi::CStr::from_ptr(p).to_string_lossy().into_owned())
    }
}

/// Finder의 **파일 참조 URL**(`file:///.file/id=…`)을 경로 URL로 푼다.
///
/// Finder ⌘C는 경로가 아니라 inode 참조 URL을 준다(08-29 실기 — 미리보기가
/// `id=…`로 보였다). 이름 표시·경로 목록(DR-6 "파일은 경로 목록만")에는 경로가
/// 필요하므로 캡처 시점에 푼다. 못 풀면 원본을 그대로 둔다(지어내지 않는다).
unsafe fn resolve_file_url(raw: &[u8]) -> Option<Vec<u8>> {
    let cstr = std::ffi::CString::new(raw).ok()?;
    unsafe {
        let s = send1(
            cls(b"NSString\0"),
            b"stringWithUTF8String:\0",
            cstr.as_ptr().cast::<core::ffi::c_void>().cast_mut(),
        );
        if s.is_null() {
            return None;
        }
        let url = send1(cls(b"NSURL\0"), b"URLWithString:\0", s);
        if url.is_null() {
            return None;
        }
        let path_url = send0(url, b"filePathURL\0");
        if path_url.is_null() {
            return None;
        }
        ns_string(send0(path_url, b"absoluteString\0")).map(String::into_bytes)
    }
}

/// `NSData` → 바이트 복사. nil이면 `None`.
unsafe fn ns_data(data: Id) -> Option<Vec<u8>> {
    if data.is_null() {
        return None;
    }
    unsafe {
        let len = send0_int(data, b"length\0") as usize;
        if len == 0 {
            return Some(Vec::new());
        }
        let bytes = send0(data, b"bytes\0");
        if bytes.is_null() {
            return None;
        }
        Some(core::slice::from_raw_parts(bytes.cast::<u8>(), len).to_vec())
    }
}

// ───────────────────────────── 읽기

/// 지금 `changeCount`만 본다 — 클립보드 데이터에는 손대지 않는 가장 싼 호출.
fn change_count() -> u64 {
    // SAFETY: nil 수신은 objc에서 0으로 돌아온다 — 그대로 0.
    unsafe {
        let pb = send0(cls(b"NSPasteboard\0"), b"generalPasteboard\0");
        if pb.is_null() {
            return 0;
        }
        send0_int(pb, b"changeCount\0") as u64
    }
}

/// 민감 표식 UTI인가 — **존재만으로** 금지(fail-closed).
fn is_conceal_marker(uti: &str) -> bool {
    matches!(
        uti,
        "org.nspasteboard.ConcealedType"
            | "org.nspasteboard.TransientType"
            | "org.nspasteboard.AutoGeneratedType"
    )
}

/// 프런트모스트 앱의 표시 이름 — 복사 직후에 부르므로 **사실상 출처 앱**이다.
///
/// ⚠️ Windows처럼 클립보드 주인을 직접 알 방법이 없다(파스텔보드에 주인 API가 없다).
/// 폴링 주기(≤1s) 안이라 근사가 어긋나는 일은 드물고, 어긋나도 표시용일 뿐이다.
///
/// ★ `NSWorkspace.frontmostApplication`을 쓰지 않는다(08-29 실기) — 그 값은
/// **메인 런루프가 도는 앱**에서만 갱신된다. 우리 감시 프로세스는 런루프가 없어
/// 시작 시점 값이 **박제**됐다(PPT·Finder 복사가 전부 iTerm2로 찍혔다).
/// `CGWindowListCopyWindowInfo`는 부를 때마다 창 서버에 물으므로 런루프가 필요 없다 —
/// 화면 맨 앞(z순서 첫) **layer 0 창**의 소유 앱이 곧 프런트모스트다.
/// (창 **이름**은 화면 기록 권한이 필요하지만 소유 앱 이름·레이어는 아니다.)
fn frontmost_app() -> Option<String> {
    /// 화면에 보이는 창만 + 데스크톱 요소 제외.
    const ON_SCREEN_ONLY: u32 = 1 << 0;
    const EXCLUDE_DESKTOP: u32 = 1 << 4;
    const UTF8: u32 = 0x0800_0100; // kCFStringEncodingUTF8
    const CF_NUMBER_INT: isize = 9; // kCFNumberIntType

    #[link(name = "CoreGraphics", kind = "framework")]
    extern "C" {
        fn CGWindowListCopyWindowInfo(option: u32, relative_to: u32) -> Id;
    }
    #[link(name = "CoreFoundation", kind = "framework")]
    extern "C" {
        fn CFRelease(cf: Id);
        fn CFArrayGetCount(arr: Id) -> isize;
        fn CFArrayGetValueAtIndex(arr: Id, idx: isize) -> Id;
        fn CFDictionaryGetValue(dict: Id, key: Id) -> Id;
        fn CFStringCreateWithCString(alloc: Id, s: *const core::ffi::c_char, enc: u32) -> Id;
        fn CFStringGetCString(s: Id, buf: *mut core::ffi::c_char, size: isize, enc: u32) -> bool;
        fn CFNumberGetValue(num: Id, ty: isize, out: *mut core::ffi::c_void) -> bool;
    }

    // SAFETY: CF 반환은 전부 nil-관용으로 검사하고, Copy/Create만 짝 맞춰 놓는다.
    unsafe {
        let list = CGWindowListCopyWindowInfo(ON_SCREEN_ONLY | EXCLUDE_DESKTOP, 0);
        if list.is_null() {
            return None;
        }
        let key_layer =
            CFStringCreateWithCString(core::ptr::null_mut(), c"kCGWindowLayer".as_ptr(), UTF8);
        let key_owner =
            CFStringCreateWithCString(core::ptr::null_mut(), c"kCGWindowOwnerName".as_ptr(), UTF8);
        let mut found = None;
        let n = CFArrayGetCount(list);
        for i in 0..n {
            let win = CFArrayGetValueAtIndex(list, i);
            if win.is_null() {
                continue;
            }
            // 일반 창은 layer 0 — 메뉴바·독·오버레이(높은 layer)를 거른다.
            let mut layer: i32 = -1;
            let num = CFDictionaryGetValue(win, key_layer);
            if num.is_null()
                || !CFNumberGetValue(num, CF_NUMBER_INT, (&raw mut layer).cast())
                || layer != 0
            {
                continue;
            }
            let name = CFDictionaryGetValue(win, key_owner);
            if name.is_null() {
                continue;
            }
            let mut buf = [0i8; 256];
            if CFStringGetCString(name, buf.as_mut_ptr(), buf.len() as isize, UTF8) {
                let cstr = core::ffi::CStr::from_ptr(buf.as_ptr());
                let s = cstr.to_string_lossy().into_owned();
                if !s.is_empty() {
                    found = Some(s);
                }
            }
            break; // z순서 첫 layer-0 창 — 그 뒤는 볼 필요 없다.
        }
        if !key_layer.is_null() {
            CFRelease(key_layer);
        }
        if !key_owner.is_null() {
            CFRelease(key_owner);
        }
        CFRelease(list);
        found
    }
}

/// 지금 클립보드를 한 벌 읽는다. 파스텔보드에 접근하지 못하면 `None`.
///
/// 여러 항목(파일 여러 개 복사)은 **표현을 순서대로 평평하게** 담는다 — 같은
/// `public.file-url`이 항목 수만큼 반복되고, [`ClipSnapshot::file_paths`]가 모아 준다.
#[must_use]
pub fn read_snapshot() -> Option<ClipSnapshot> {
    // SAFETY: 반환 객체는 전부 autorelease — 풀을 짝 맞춰 닫는다.
    unsafe {
        let pool = objc_autoreleasePoolPush();
        let snap = read_snapshot_inner();
        objc_autoreleasePoolPop(pool);
        snap
    }
}

/// # Safety
/// autorelease 풀 안에서 불러야 한다.
unsafe fn read_snapshot_inner() -> Option<ClipSnapshot> {
    unsafe {
        let pb = send0(cls(b"NSPasteboard\0"), b"generalPasteboard\0");
        if pb.is_null() {
            return None;
        }
        let seq = send0_int(pb, b"changeCount\0") as u64;

        // ★ 표식은 파스텔보드 전체 types에서 먼저 본다 — 표식이 있으면 바이트를 읽지 않는다.
        let mut concealed = false;
        let pb_types = send0(pb, b"types\0");
        if !pb_types.is_null() {
            let n = send0_int(pb_types, b"count\0") as usize;
            for i in 0..n {
                let t = send1_idx(pb_types, b"objectAtIndex:\0", i);
                if ns_string(t).is_some_and(|u| is_conceal_marker(&u)) {
                    concealed = true;
                    break;
                }
            }
        }

        let items = send0(pb, b"pasteboardItems\0");
        if items.is_null() {
            return None;
        }
        let item_n = send0_int(items, b"count\0") as usize;
        let mut reps = Vec::new();
        for i in 0..item_n {
            let item = send1_idx(items, b"objectAtIndex:\0", i);
            if item.is_null() {
                continue;
            }
            let types = send0(item, b"types\0");
            if types.is_null() {
                continue;
            }
            let type_n = send0_int(types, b"count\0") as usize;
            for j in 0..type_n {
                let t = send1_idx(types, b"objectAtIndex:\0", j);
                let Some(name) = ns_string(t) else { continue };
                // ⚠️ 표식이 있으면 **이름만** 담는다(fail-closed — 내용을 읽지 않는다).
                //   지연 제공(promised) 타입이 nil을 주면 그것도 이름만 남긴다 —
                //   Windows의 핸들 포맷과 같은 취급이다(분류는 이름만 본다).
                let mut data = if concealed {
                    Vec::new()
                } else {
                    send1(item, b"dataForType:\0", t)
                        .pipe(|d| ns_data(d))
                        .unwrap_or_default()
                };
                if name == "public.file-url" && !data.is_empty() {
                    data = resolve_file_url(&data).unwrap_or(data);
                }
                reps.push(RawRep { format: name, data });
            }
        }

        // ★ 항목 API가 비면 **파스텔보드 수준으로 폴백**한다(08-29 실기 — AppleScript의
        //   `set the clipboard to (POSIX file …)` 직후 `pasteboardItems`가 그 changeCount
        //   동안 빈 배열로 고정되는 일이 있다. 신선한 프로세스는 같은 내용을 읽는다).
        //   pb-level `types`/`dataForType:`은 첫 항목만 보는 구식 경로지만, 항목이 아예
        //   안 보이는 것보다는 낫다 — 다중 파일은 항목 API가 정상일 때만 전부 온다.
        if reps.is_empty() && !pb_types.is_null() {
            let n = send0_int(pb_types, b"count\0") as usize;
            for i in 0..n {
                let t = send1_idx(pb_types, b"objectAtIndex:\0", i);
                let Some(name) = ns_string(t) else { continue };
                if is_conceal_marker(&name) {
                    continue;
                }
                let mut data = if concealed {
                    Vec::new()
                } else {
                    send1(pb, b"dataForType:\0", t)
                        .pipe(|d| ns_data(d))
                        .unwrap_or_default()
                };
                if name == "public.file-url" && !data.is_empty() {
                    data = resolve_file_url(&data).unwrap_or(data);
                }
                reps.push(RawRep { format: name, data });
            }
        }

        Some(ClipSnapshot {
            reps,
            source_app: frontmost_app(),
            concealed,
            seq,
        })
    }
}

/// `.pipe` 흉내 — objc 호출 사슬을 한 줄로 잇기 위한 내부 도우미.
trait Pipe: Sized {
    fn pipe<T>(self, f: impl FnOnce(Self) -> T) -> T {
        f(self)
    }
}
impl<T> Pipe for T {}

// ───────────────────────────── 감시 루프

/// 감시를 켠다 — 전용 스레드에서 `changeCount`를 적응형 주기로 폴링한다.
///
/// 창이 필요 없으므로(Windows와 달리) 스레드 하나가 전부다.
pub fn start(sink: Sink) -> Result<(), WatchError> {
    std::thread::Builder::new()
        .name("nclip-watch-mac".into())
        .spawn(move || poll_loop(&sink))
        .map_err(|e| WatchError::Os(format!("감시 스레드 생성 실패: {e}")))?;
    Ok(())
}

/// `NEXA_CLIP_DIAG=1`일 때만 stderr로 진단을 찍는다(watch_win의 diag와 동일 규약).
fn diag(msg: &str) {
    if std::env::var_os("NEXA_CLIP_DIAG").is_some() {
        eprintln!("[diag] {msg}");
    }
}

/// ★ 안정화 읽기(09-04 mac 실기 — "한 번 복사가 두 항목") — 앱이 표현을 **여러 단계로
/// 게시**하면(`changeCount` 연쇄 +N) 첫 단계를 읽은 부분 스냅숏과 최종본이 서로 달라
/// 같은 복사가 두 항목이 된다(Windows Sublime 연타 증식 09-01과 동일 계열).
/// `watch_win::read_settled`와 같은 문법 — **두 번 연속 같게 읽힐 때까지**(30ms × 최대 4회).
fn read_settled() -> Option<ClipSnapshot> {
    let mut cur = read_snapshot()?;
    for _ in 0..4 {
        std::thread::sleep(std::time::Duration::from_millis(30));
        let Some(next) = read_snapshot() else {
            return Some(cur); // 재읽기 실패 — 지금 것을 쓴다(없는 것보다 낫다).
        };
        let same = next.seq == cur.seq
            && cur.reps.len() == next.reps.len()
            && cur
                .reps
                .iter()
                .zip(&next.reps)
                .all(|(a, b)| a.format == b.format && a.data == b.data);
        if same {
            return Some(next);
        }
        diag(&format!(
            "아직 자리 잡는 중(seq {} → {}) — 재확인",
            cur.seq, next.seq
        ));
        cur = next;
    }
    Some(cur)
}

fn poll_loop(sink: &Sink) {
    // 시작 시점의 내용은 "새 복사"가 아니다 — 지금 번호를 기준선으로 삼는다.
    let mut last = change_count();
    let mut idle_ticks: u32 = 0;
    loop {
        std::thread::sleep(std::time::Duration::from_millis(interval_ms(idle_ticks)));
        let cc = change_count();
        if cc == last {
            idle_ticks = idle_ticks.saturating_add(1);
            continue;
        }
        diag(&format!("changeCount {last} → {cc}"));
        // 변화 감지 — 내용을 읽는다(★ 자리 잡은 최종본만 — 아래 read_settled).
        match read_settled() {
            // ★ 결함 ⑫의 교훈: **내용 없는 스냅숏은 미처리** — 번호를 올리지 않고
            //   다음 틱에 다시 읽는다(비우고→채우는 틈을 읽었을 수 있다).
            //   표식(concealed)이 있는 것은 이름만 있어도 **처리된 것**이다 — 게이트가 버린다.
            Some(snap) if snap.concealed || !snap.reps.is_empty() => {
                diag(&format!("전달 seq={} 표현 {}개", snap.seq, snap.reps.len()));
                last = snap.seq.max(last.wrapping_add(1));
                idle_ticks = 0;
                sink(snap);
            }
            Some(snap) => {
                diag(&format!("내용 없는 스냅숏(seq {}) — 재시도", snap.seq));
                idle_ticks = 0;
            }
            None => {
                diag("파스텔보드 읽기 실패 — 재시도");
                idle_ticks = 0;
            }
        }
    }
}

/// 적응형 주기 — 활동 직후 200ms, 5초 조용하면 100ms씩 늘려 1s에서 멈춘다.
fn interval_ms(idle_ticks: u32) -> u64 {
    if idle_ticks < IDLE_AFTER_TICKS {
        ACTIVE_MS
    } else {
        // +1 — 유휴에 **진입한 첫 틱부터** 늘기 시작해야 한다(0이면 진입이 무의미하다).
        (ACTIVE_MS + (u64::from(idle_ticks - IDLE_AFTER_TICKS) + 1) * IDLE_STEP_MS).min(IDLE_MAX_MS)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// 적응형 주기는 활동 200ms → 유휴 1s 사이만 오간다(DR-9 — 상주 비용 상한).
    #[test]
    fn interval_ramps_from_active_to_idle_cap() {
        assert_eq!(interval_ms(0), ACTIVE_MS);
        assert_eq!(interval_ms(IDLE_AFTER_TICKS - 1), ACTIVE_MS);
        assert!(interval_ms(IDLE_AFTER_TICKS) > ACTIVE_MS);
        assert_eq!(interval_ms(10_000), IDLE_MAX_MS);
        // 오버플로 없이 상한에 머문다.
        assert_eq!(interval_ms(u32::MAX), IDLE_MAX_MS);
    }

    /// 민감 표식 셋은 **존재만으로** 금지다(docs/20 §297 · fail-closed).
    #[test]
    fn conceal_markers_are_recognized() {
        assert!(is_conceal_marker("org.nspasteboard.ConcealedType"));
        assert!(is_conceal_marker("org.nspasteboard.TransientType"));
        assert!(is_conceal_marker("org.nspasteboard.AutoGeneratedType"));
        assert!(!is_conceal_marker("public.utf8-plain-text"));
    }

    /// 실 파스텔보드 왕복 — `changeCount`가 읽히고, 스냅숏이 그 번호를 담는다.
    ///
    /// CI(headless)에서도 파스텔보드는 있다 — 없으면 `None`이어도 통과(정직한 실패).
    #[test]
    fn read_now_reports_seq_when_available() {
        let cc = change_count();
        if cc == 0 {
            return; // 파스텔보드 접근 불가 환경 — 여기서 검증할 것이 없다.
        }
        if let Some(snap) = read_snapshot() {
            assert!(snap.seq >= cc, "스냅숏 번호가 관측 번호보다 뒤일 수 없다");
        }
    }
}
